# Generated by Django 4.0.2 on 2022-03-01 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_kit_remove_copter_description_alter_copter_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('copter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.copter')),
            ],
        ),
        migrations.CreateModel(
            name='Charging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='charging date')),
                ('charge', models.CharField(choices=[('C', 'Charge'), ('D', 'Double charge')], default='C', max_length=1)),
                ('copter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.copter')),
            ],
            options={
                'ordering': ('-date', 'charge'),
            },
        ),
    ]
